version: '3.8'

services:
  database:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_DATABASE: demo
      MYSQL_USER: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d
